### ISSUE TITLE
Export HelmetOptions interface

### ISSUE THREAD

**Issue by knor-el-snor** [helmetjs/helmet#279]
I'm not sure whether it's done intentionally but I personally need the interface (which used to be exported when it was within DefinitelyTyped) since I wrap this into a sort of `setupServer` functionality taking on a couple of object options including `helmet`. 

The following seems impossible (besides copy/pasting from the source code) unless exporting this interface

```
helmet?: HelmetOptions;
```

I've personally forked the repository & exported the interface to make it work but wanted to check first whether it was done on purpose before creating a pull request.

**Comment by EvanHahn** [comment]
Unfortunately, I won't be able to export `HelmetOptions` in this major version without making a breaking change. Would something like this work for you?

```typescript
type HelmetOptions = Parameters<typeof helmet>[0];
```

**Comment by EvanHahn** [comment]
I'm going to close this issue because I think this has been resolved, but let me know if that's wrong and I'll reopen.

**Comment by EvanDarwin** [comment]
Hi there, even with the `Parameters` lookup, I still receive an error on TypeScript 4.1.3:
```
TS4032: Property 'helmet' of exported interface has or is using name 'HelmetOptions' from private module ...
```

**Comment by EvanHahn** [comment]
@EvanDarwin Could you include a code snippet that reproduces your problem along with your `tsconfig.json`?

**Comment by EvanDarwin** [comment]
I tried to reproduce this in a separate codebase and was unable to, and it now seems the original codebase is working fine with your recommended solution, so... my apologies.

**Comment by EvanHahn** [comment]
No problem at all! Feel free to open a new issue if you run into anything else.

**Comment by brandon-leapyear** [comment]
Why would exporting the interface be a breaking change? The workaround is fine for now, but it would be preferable to just import the type

**Comment by EvanHahn** [comment]
Exporting it caused issues (see #235) with certain TypeScript configurations.

I'll likely be able to export it in Helmet 5, however.

**Comment by TrejGun** [comment]
@EvanDarwin please reopen this issue and add to v5 milestone

**Comment by EvanHahn** [comment]
I'll plan to revisit the export story in Helmet 5. Follow along in #320.

**Comment by EvanHahn** [comment]
I just released Helmet v5.0.0-beta.1 which addresses this. You can now `import helmet, { HelmetOptions } from 'helmet'`. Please give it a try with `npm install helmet@5.0.0-beta.1` and let me know if there are any problems! Feel free to reply here or email me@evanhahn.com with any feedback.
